logfile: weathercollect.log

influxdb:
  user: username
  password: password
  host: 127.0.0.1
  port: 8086
  dbname: temperaturedb
  measurename: netatmo

netatmo:
  authtoken: 52d42f05177759882c8b456a|753293ecafa4f4b1a9604611adc998e9
  nodes:
    - device_id:      70:ee:50:13:20:6a
      temp_module_id: 02:00:00:2c:c0:a8
      rain_module_id: 05:00:00:01:76:ac
    - device_id:      70:ee:50:13:54:28
      temp_module_id: 02:00:00:13:62:14
    - device_id:      70:ee:50:01:29:fc
      temp_module_id: 02:00:00:01:01:56